name: Documentation
on:
    pull_request:
      branches:
        - master
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.x
      - run: pip install pydantic==1.8.2
      - run: pip install linecache2==1.0.0
      - run: pip install scipy==1.7.3
      - run: pip install matplotlib==3.3.0
      - run: pip install mkdocs-material==8.0.5
      - run: pip install mkdocstrings==0.16.2
      - run: mkdocs gh-deploy --force